spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://34.40.11.147:8888
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: env
ENVIRONMENT: DEFAULT