spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://35.242.213.108:8888
  profiles:
    active: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
  address: 0.0.0.0