spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://35.198.176.191:8888
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: env
ENVIRONMENT: DEFAULT