spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://34.159.242.142:8888
  profiles:
    active: test
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true