version: '3.8'

services:
  # Microservices

  user-service:
    image: user-service:dev
    build: ./services/user-service
    ports:
      - "8082:8082"  # Consistent port mapping
    networks:
      - microservices-net
    environment:
      - DB_URL=jdbc:postgresql://postgres1:5432/dev_db
      - SPRING_PROFILES_ACTIVE=dev

  price-data-service:
    image: price-data-service:dev
    build: ./services/price-data-service
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    environment:
      - DB_URL=jdbc:postgresql://postgres2:5435/dev_db2
      - SPRING_PROFILES_ACTIVE=dev

  api-gateway-service:
    image: api-gateway-service:dev
    build: ./services/api-gateway-service
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - user-service
      - price-data-service

  # SQL Databases
  postgres1:
    container_name: postgres_1
    image: postgres:13.3
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: dev_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgres2:
    container_name: postgres_2
    image: postgres:13.3
    environment:
      POSTGRES_USER: dev_user2
      POSTGRES_PASSWORD: dev_pass2
      POSTGRES_DB: dev_db2
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres2:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGAMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

# Networks
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres1:
  postgres2:
  pgadmin: