apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName : ksa-cloud-sql
      containers:
      - name: user-service
        image: europe-west3-docker.pkg.dev/crypto-price-tracker-447719/cpt-mservices-repo/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_EXPIRATION 
        - name: PORT
          value: "8082"
        - name: INSTANCE_CONNECTION_NAME
          value: crypto-price-tracker-447719:europe-west3:postgress96
        - name: DB_PORT
          value: "5432"  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cse-cloud-sql-secrets
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cse-cloud-sql-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cse-cloud-sql-secrets
              key: database
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        resources:
          limits: 
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"