spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/users/**
        - id: price-data-service
          uri: http://price-data-service:8080
          predicates:
            - Path=/prices/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service/.well-known/jwks.json # Replace with your JWKS URL
server:
  port: 8222