spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**, /api/admin/**
          filters:
            - PreserveHostHeader

        - id: price-data-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/prices/**, /dashboard, /export
          filters:
            - PreserveHostHeader

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics