spring:
  application:
    name: price-data-service
  datasource:
    url: jdbc:postgresql://localhost:5433/dev_price_db
    username: dev_user
    password: dev_pass
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: debug
    org:
      springframework: info