spring:
  application:
    name: price-data-service
  datasource:
    url: jdbc:postgresql://postgres2:5435/dev_db2
    username: dev_user2
    password: dev_pass2
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: debug

coingecko:
  api:
    base-url: https://api.coingecko.com/api/v3