spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_user
    password: dev_pass
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: debug

    
jwt:
  secret: ${JWT_SECRET:c2VjcmV0LWtleS0yNTYtYml0cy1sb25nLWZvci1qd3QtdG9rZW4tc2lnbmluZy1pbi1jcnlwdG8tdHJhY2tlcg==}
  expiration: ${JWT_EXPIRATION:86400000}