spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/user_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: debug
    org.springframework: info
