spring:
  datasource:
    url:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      sql:
        instance-connection-name: ${INSTANCE_CONNECTION_NAME}
        database-name: ${USERS_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init: 
      mode: always
logging:
  level:
    root: info
    org.springframework: warn
ENVIRONMENT: testvariable
