spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: dev_user
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop 
logging:
  level:
    root: debug
    org:
      springframework: info