spring:
  application:
    name: price-data-service
  config:
    import: optional:configserver:http://35.242.213.108:8888
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081
  address: 0.0.0.0
coingecko:
  api:
    base-url: https://api.coingecko.com/api/v3