spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reghima96/cse-crypto-price-tracker.git
          search-paths:
            - config
  profiles:
    active: git
server:
  port:
    8888
