name: CI for Development Branch

on:
  push:
    branches:
      - development

jobs:
  ci-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [config-server, api-gateway-service, user-service, price-data-service]

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      # Step 3: Give execute permissions to mvnw
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      # Step 3: Build and Test Each Service
      - name: Build and Test ${{ matrix.service }}
        working-directory: services/${{ matrix.service }}
        run: ./mvnw clean test
